name: CI

on:
  push:
  workflow_dispatch:

jobs:
  clang-tidy:
    strategy:
      fail-fast: false
      matrix:
        check: [
          'clang-*',
          'bugprone-*',
          'cppcoreguidelines-*',
          'modernize-*',
          'performance-*',
          'readability-*',
        ]
        runner: [
          windows-2019,
          windows-2022,
          ubunntu-latest,
          macos-latest
        ]

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: macos setup
        if: runner.os == 'macOS'
        run: |
          brew install llvm
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

      - name: windows-2019 setup
        if: matrix.runner == 'windows-2019'
        shell: cmd
        run: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\bin >> $GITHUB_PATH

      - name: windows-2022 setup
        if: matrix.runner == 'windows-3022'
        shell: cmd
        run: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin >> $GITHUB_PATH

      - name: Run clang-tidy
        shell: bash
        run: clang-tidy --checks="-*,${{ matrix.check }}" main.cpp
