name: CI

on:
  push:
  workflow_dispatch:

jobs:
  clang-tidy:
    strategy:
      fail-fast: false
      matrix:
        check: [
          modernize-avoid-bind,
          modernize-avoid-c-arrays
          modernize-concat-nested-namespaces,
          modernize-deprecated-headers,
          modernize-deprecated-ios-base-aliases,
          modernize-loop-convert,
          modernize-macro-to-enum,
          modernize-make-shared,
          modernize-make-unique,
          modernize-pass-by-value,
          modernize-raw-string-literal,
          modernize-redundant-void-arg,
          modernize-replace-auto-ptr,
          modernize-replace-disallow-copy-and-assign-macro,
          modernize-replace-random-shuffle,
          modernize-return-braced-init-list,
          modernize-shrink-to-fit,
          modernize-type-traits,
          modernize-unary-static-assert,
          modernize-use-auto,
          modernize-use-bool-literals,
          modernize-use-constraints,
          modernize-use-default-member-init,
          modernize-use-emplace,
          modernize-use-equals-default,
          modernize-use-equals-delete,
          modernize-use-nodiscard,
          modernize-use-noexcept,
          modernize-use-nullptr,
          modernize-use-override,
          modernize-use-std-print,
          modernize-use-trailing-return-type,
          modernize-use-transparent-functors,
          modernize-use-uncaught-exceptions,
          modernize-use-using
        ]
        runner: [
          windows-latest,
          ubuntu-latest
        ]
        clang-tidy: [clang-tidy]
        include:
          - runner: windows-latest
            clang-tidy: C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        shell: bash
        run: '"${{ matrix.clang-tidy }}" --checks="${{ matrix.check }}" main.cpp --'
