name: CI

on:
  push:
  workflow_dispatch:

jobs:
  clang-tidy:
    strategy:
      fail-fast: false
      matrix:
        check: [
          'clang-*',
          'bugprone-*',
          'cppcoreguidelines-*',
          'modernize-*',
          'performance-*',
          'readability-*',
        ]
        runner: [
          windows-2019,
          windows-2022,
          ubuntu-latest
        ]
        include:
          - runner: windows-2019
            clang-tidy: C:\Program Files (x86)\Microsoft Visual Studio\2019\\Enterprise\VC\Tools\Llvm\bin\clang-tidy

          - runner: windows-2022
            clang-tidy: C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy

          - runner: ubuntu-latest
            clang-tidy: clang-tidy

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        shell: bash
        run: "${{ matrix.clang-tidy }}" --checks="${{ matrix.check }}" main.cpp --
