name: CI

on:
  push:
  workflow_dispatch:

jobs:
  windows-install-llvm-version:
    strategy:
      fail-fast: false
      matrix:
        version: [
          15.0.4,
          15.0.5,
          15.0.7,
          16.0.0,
          16.0.1,
          16.0.2,
          16.0.3,
          16.0.4,
          16.0.5,
          16.0.6,

        ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          choco install llvm --version ${{ matrix.version }} --force

      - shell: bash
        run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --

  windows-gha-bundled-llvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --

  windows-vs-bundled-llvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run:  |
          "C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --version
          "C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --checks="-*,modernize-use-nullptr" main.cpp --

  windows-vs2019-llvm:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run:  |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --version
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --checks="-*,modernize-use-nullptr" main.cpp --

  ubuntu-gha-llvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --
