name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        year: [2019, 2022]

    runs-on: windows-${{ matrix.year }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate and Build
        shell: cmd
        run: |
          PATH=C:\Program Files\Microsoft Visual Studio\${{ matrix.year }}\Enterprise\VC\Tools\Llvm\bin;%PATH%
          cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_CXX_FLAGS=-Wno-everything -fuse-ld=lld-link.exe" "-DCMAKE_CXX_CLANG_TIDY=clang-tidy;-checks=modernize-*"
          cmake --build build --config Debug
