name: CI

on:
  push:
  workflow_dispatch:

jobs:
  windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        shell: cmd
        run: |
          PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\bin;%PATH%
          clang-tidy main.cpp --

  windows-2022:
    strategy:
      matrix:
        check: [
          'clang*',
          'bugprone*',
          'cppcoreguidelines*',
          'modernize*',
          'performance*',
          'readability*',
        ]
    runs-on: windows-2022 (${{ matrix.check }})
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        shell: cmd
        run: |
          PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin;%PATH%
          clang-tidy main.cpp -- --checks="-*,${{ matrix.check }}"

  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        run: |
          clang-tidy main.cpp --

  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-tidy
        run: |
          brew install llvm
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

      - name: Run clang-tidy
        run: |
          clang-tidy main.cpp --
