name: CI

on:
  push:
  workflow_dispatch:

jobs:
  windows-install-llvm-version:
    strategy:
      matrix:
        version: [
          15.0.1,
          15.0.2,
          15.0.3,
          15.0.4,
          15.0.5,
          15.0.6,
          15.0.7
        ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          choco install llvm --version ${{ matrix.version }} --force

      - shell: bash
        run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --

  windows-gha-bundled-llvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --

  windows-vs-bundled-llvm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run:  |
          "C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --version
          "C:\Program Files\Microsoft Visual Studio\2022\\Enterprise\VC\Tools\Llvm\bin\clang-tidy" --checks="-*,modernize-use-nullptr" main.cpp --

  ubuntu-gha-bundled-llvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          clang-tidy --version
          clang-tidy --checks="-*,modernize-use-nullptr" main.cpp --
